---
  
  - debug: var=rvar_wxconfig_ports_https_list verbosity=3

  - set_fact: 
      configure_integrationserver_wxconfig_set_ports_https_changed: false

  - block:
      
      - name: set template config
        include_tasks: set_wxconfig_template.yml
        vars:
          _wxconfig_template_file: as-port-https-template.xml
          _wxconfig_target_filename_prefix: wxconfigs-port-https
   
      - name: Set changed flag to true if any mutating operation did change
        set_fact: 
          configure_integrationserver_wxconfig_set_ports_https_changed: "{{ _wxconfig_template_operation_changed }}"

    when: rvar_wxconfig_ports_https_list is defined and rvar_wxconfig_ports_https_list|length > 0
