---

  - debug: var=rvar_wxconfig_cachemanagers_list verbosity=3

  - set_fact: 
      configure_integrationserver_wxconfig_set_cache_managers_changed: false

  - block:
      
      - name: set template config
        include_tasks: set_wxconfig_template.yml
        vars:
          _wxconfig_template_file: as-cache-managers-template.xml
          _wxconfig_target_filename_prefix: wxconfigs-cache-managers
   
      - name: Set changed flag to true if any mutating operation did change
        set_fact: 
          configure_integrationserver_wxconfig_set_cache_managers_changed: "{{ _wxconfig_template_operation_changed }}"

    when: rvar_wxconfig_cachemanagers_list is defined and rvar_wxconfig_cachemanagers_list|length > 0
