---
---

  - debug: var=rvar_wxconfig_groups_list verbosity=3
  - debug: var=rvar_wxconfig_acl_list verbosity=3

  - set_fact: 
      configure_integrationserver_wxconfig_set_accesscontrol_changed: false

  - block:
      
      - name: set template config
        include_tasks: set_wxconfig_template.yml
        vars:
          _wxconfig_template_file: as-access-control-template.xml
          _wxconfig_target_filename_prefix: wxconfigs-access-control
   
      - name: Set changed flag to true if any mutating operation did change
        set_fact: 
          configure_integrationserver_wxconfig_set_accesscontrol_changed: "{{ _wxconfig_template_operation_changed }}"

    when: (rvar_wxconfig_groups_list is defined and rvar_wxconfig_groups_list|length > 0) or (rvar_wxconfig_acl_list is defined and rvar_wxconfig_acl_list|length > 0) or (rvar_wxconfig_service_acl_mapping_list is defined and rvar_wxconfig_service_acl_mapping_list|length > 0)
