---
  
  - debug: var=rvar_wxconfig_adapter_connections_list verbosity=3

  - set_fact: 
      configure_integrationserver_wxconfig_set_adapter_connections_changed: false

  - block:
      
      - name: set template config
        include_tasks: set_wxconfig_template.yml
        vars:
          _wxconfig_template_file: as-art-template.xml
          _wxconfig_target_filename_prefix: wxconfigs-art
   
      - name: Set changed flag to true if any mutating operation did change
        set_fact: 
          configure_integrationserver_wxconfig_set_adapter_connections_changed: "{{ _wxconfig_template_operation_changed }}"

    when: rvar_wxconfig_adapter_connections_list is defined and rvar_wxconfig_adapter_connections_list|length > 0
