---
  
  - debug: var=rvar_wxconfig_messaging_wmalias_list verbosity=3
  - debug: var=rvar_wxconfig_messaging_wmtriggers_list verbosity=3
  - debug: var=rvar_wxconfig_messaging_jndi_list verbosity=3
  - debug: var=rvar_wxconfig_messaging_jmsalias_list verbosity=3
  - debug: var=rvar_wxconfig_messaging_jmstriggers_list verbosity=3

  - set_fact: 
      configure_integrationserver_wxconfig_set_is_messaging_changed: false

  - block:
      
      - name: set template config
        include_tasks: set_wxconfig_template.yml
        vars:
          _wxconfig_template_file: as-is-messaging-template.xml
          _wxconfig_target_filename_prefix: wxconfigs-is-messaging
   
      - name: Set changed flag to true if any mutating operation did change
        set_fact: 
          configure_integrationserver_wxconfig_set_is_messaging_changed: "{{ _wxconfig_template_operation_changed }}"

    when: >
      rvar_wxconfig_messaging_wmalias_list is defined and rvar_wxconfig_messaging_wmalias_list|length > 0 or 
      rvar_wxconfig_messaging_wmtriggers_list is defined and rvar_wxconfig_messaging_wmtriggers_list|length > 0 or 
      rvar_wxconfig_messaging_jndi_list is defined and rvar_wxconfig_messaging_jndi_list|length > 0 or 
      rvar_wxconfig_messaging_jmsalias_list is defined and rvar_wxconfig_messaging_jmsalias_list|length > 0 or 
      rvar_wxconfig_messaging_jmstriggers_list is defined and rvar_wxconfig_messaging_jmstriggers_list|length > 0