---
  
  - debug: var=rvar_wxconfig_jdbc verbosity=3

  - set_fact: 
      configure_integrationserver_wxconfig_set_jdbc_pools_changed: false

  - block:
      
      - name: set template config
        include_tasks: set_wxconfig_template.yml
        vars:
          _wxconfig_template_file: as-jdbc-template.xml
          _wxconfig_target_filename_prefix: wxconfigs-jdbc
   
      - name: Set changed flag to true if any mutating operation did change
        set_fact: 
          configure_integrationserver_wxconfig_set_jdbc_pools_changed: "{{ _wxconfig_template_operation_changed }}"

    when: rvar_wxconfig_jdbc is defined and rvar_wxconfig_jdbc.keys() | length > 0
