---
  
  - debug: var=rvar_wxconfig_keytruststore_list verbosity=3

  - set_fact: 
      configure_integrationserver_wxconfig_set_keyandtrust_stores_changed: false

  - block:
      
      - name: set template config
        include_tasks: set_wxconfig_template.yml
        vars:
          _wxconfig_template_file: as-keyandtrust-stores-template.xml
          _wxconfig_target_filename_prefix: wxconfigs-keyandtrust-stores
   
      - name: Set changed flag to true if any mutating operation did change
        set_fact: 
          configure_integrationserver_wxconfig_set_keyandtrust_stores_changed: "{{ _wxconfig_template_operation_changed }}"

    when: rvar_wxconfig_keytruststore_list is defined and rvar_wxconfig_keytruststore_list|length > 0
