---

### Needs:
### - service_name

- name: fail if service_name not specified
  fail: 
    msg: "service_name not specified...cannot create."
  when: service_name is not defined or service_name == ""

- name: get service facts
  service_facts:

- name: Format service name to {{ service_name }}.service for service_facts lookup
  set_fact:
    service_name_index: "{{ service_name }}.service"

- name: Print debug message
  debug:
    msg: "Service {{ service_name }} is not found...no need to delete"
  when: ansible_facts.services[service_name_index] is not defined

- name: delete if service is found
  block:
    
    - name: Print debug message
      debug:
        msg: "Service {{ service_name }} will be deleted"

    - name: Stop and disable service state
      ansible.builtin.systemd: 
        name: "{{ service_name }}"
        state: "stopped"
        enabled: no

    - name: Delete systemd service files
      file:
        path: "{{ systemd_file_delete }}"
        state: absent
      with_items:
        - "/etc/systemd/system/{{ service_name_index }}"
        - "/etc/systemd/system/{{ service_name_index }}.d"
        - "/usr/lib/systemd/system/{{ service_name_index }}"
      loop_control:
        loop_var: systemd_file_delete

    - name: force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: final systemd reset failed
      shell: "systemctl reset-failed"

    # finally, fail if service found
    - name: get service facts
      service_facts:

    - name: fail if service is still found
      fail: 
        msg: "service {{ service_name }} still found...should not be...investigate!"
      when: ansible_facts.services[service_name_index] is defined
  
  when: ansible_facts.services[service_name_index] is defined