---

  - name: "Update config file {{ rvar_wrapper_file }} with jvm_params params to remove"
    lineinfile:
      path: "{{ rvar_wrapper_file }}"
      regexp: "{{ item }}"
      state: absent
    with_items: "{{ jvm_params_regex_patterns }}"
    when: jvm_params_regex_patterns is defined and (jvm_params_regex_patterns|length > 0)
