---

  - debug: var=rvar_wrapper_file verbosity=1
  
  - name: fail if mandatory params not specified
    fail: 
      msg: "wrapper file source path is not defined...should be!"
    when: rvar_wrapper_file is not defined
  
  - name: check if wrapper path exists
    stat: 
      path: "{{ rvar_wrapper_file }}"
    register: check_wrapperfile

  - name: fail if wrapper file does not exists
    fail:
      msg: "wrapper file source path does not exist..."
    when: not check_wrapperfile.stat.exists

  - name: "Update config file {{ rvar_wrapper_file }} with jvm_params params to remove"
    lineinfile:
      path: "{{ rvar_wrapper_file }}"
      regexp: "(?i)^(.*{{ item }}.*)$"
      line: '# \1'
      backrefs: yes
      state: present
    with_items: "{{ rvar_jvm_params_regex_patterns }}"
    when: rvar_jvm_params_regex_patterns is defined and (rvar_jvm_params_regex_patterns|length > 0)
