---

  - name: "Update config file {{ rvar_wrapper_file }} with rvar_jvm_params params if defined"
    lineinfile:
      state: present
      path: "{{ rvar_wrapper_file }}"
      regexp: "^{{ item.key | replace('.','\\.') }}="
      insertafter: "^#{{ item.key | replace('.','\\.') }}="
      line: "{{ item.key }}={{ item.value }}"
    with_dict: "{{ rvar_jvm_params }}"
    when: rvar_jvm_params is defined and (rvar_jvm_params|length > 0)