---

  - name: "Update config file {{ rvar_wrapper_file }} with jvm_heap_min param if defined"
    lineinfile:
      path: "{{ rvar_wrapper_file }}"
      regexp: '^{{ item.key }}'
      insertafter: '^#{{ item.key }}'
      line: "{{ item.key }}={{ item.value }}"
    with_dict:
      "wrapper.java.initmemory": "{{ jvm_heap_min }}"
    when: jvm_heap_min is defined and jvm_heap_min != ""

  - name: "Update config file {{ rvar_wrapper_file }} with jvm_heap_max param if defined"
    lineinfile:
      path: "{{ rvar_wrapper_file }}"
      regexp: '^{{ item.key }}'
      insertafter: '^#{{ item.key }}'
      line: "{{ item.key }}={{ item.value }}"
    with_dict:
      "wrapper.java.maxmemory": "{{ jvm_heap_max }}"
    when: jvm_heap_max is defined and jvm_heap_max != ""

  - name: cleanup facts
    set_fact:
      rvar_wrapper_file: ""
      jvm_heap_min: ""
      jvm_heap_max: ""