---

## note: the remote_source_path should be a path that exists on the remote target machine
## expected format
  # remote_source_path: "path/to/a/package/zipfile"
  # target_is_instance_name: default
  # target_is_package_name: "packagename"
  # force_reinstall: yes/no

  - name: Single Package to install
    debug: var=rvar_is_install_package_single verbosity=3

  - name: Set changed flag to false if not defined
    set_fact: 
      configure_integrationserver_install_package_changed: false
    when: configure_integrationserver_install_package_changed is not defined

  - name: fail if mandatory params not specified
    fail:
      msg: "A mandatory param was not defined, cannot do anything."
    when: item is not defined
    with_items:
      - "{{ rvar_is_install_package_single }}"
      - "{{ rvar_is_install_package_single.remote_source_path }}"
      - "{{ rvar_is_install_package_single.target_is_instance_name }}"

  - name: set temp local download path
    set_fact: 
      __package_remote_source_path: "{{ rvar_is_install_package_single.remote_source_path }}"

  - name: set target package name from the passed-in variables
    set_fact: 
      __target_package_name: "{{ rvar_is_install_package_single.target_is_package_name }}"
    when: rvar_is_install_package_single.target_is_package_name is defined and rvar_is_install_package_single.target_is_package_name != ""

  - name: OR default package name to the name of the file on the remote location
    set_fact: 
      __target_package_name: "{{ (rvar_is_install_package_single.bucket_path | basename | splitext)[0] }}"
    when: rvar_is_install_package_single.target_is_package_name is not defined or rvar_is_install_package_single.target_is_package_name == ""

  - name: Set the local target package path
    set_fact: 
      __target_package_dir: "{{ _runtime_instance_package_home }}/{{ __target_package_name }}"

  - name: Set the target instance for this package install in order to get the riht path for the packages folder
    set_fact: 
      __target_instance_name: "{{ rvar_is_install_package_single.target_is_instance_name }}"
  
  - name: check if we should force re-install the package even if it exists
    set_fact: 
      __target_force_reinstall_package: "{{ rvar_is_install_package_single.force_reinstall | default(false, true) }}"

  - debug:
      var: "{{ item }}"
      verbosity: 1
    with_items:
      - __package_remote_source_path
      - __target_instance_name
      - __target_package_dir
      - __target_force_reinstall_package

  - name: check 1 if package already installed
    stat: 
      path: "{{ __target_package_dir }}/manifest.rel"
    register: check_package_installed_1

  - name: check 2 if package already installed
    stat: 
      path: "{{ __target_package_dir }}/manifest.v3"
    register: check_package_installed_2

  - debug: var=check_package_installed_1 verbosity=3
  - debug: var=check_package_installed_2 verbosity=3

  - name: is package installed?
    set_fact: 
      check_package_installed: "{{ check_package_installed_1.stat.exists or check_package_installed_2.stat.exists }}"

  - debug: var=check_package_installed verbosity=3

  - debug: 
      msg: "{{ __target_package_name }} already exists in Integration Server instance...will not re-install!"
      verbosity: 1
    when: (check_package_installed | bool) == true or (__target_force_reinstall_package | default() | bool) == false

  - name: Install package only if it's not already there, or will re-install if force_reinstall var is set
    block:

      - debug: 
          msg: "Re-installing package {{ __target_package_name }} in Integration Server instance \"{{ __target_instance_name }}\""
          verbosity: 1
        when: (check_package_installed | bool) and (__target_force_reinstall_package | bool)
      
      - debug: 
          msg: "Installing new package {{ __target_package_name }} in Integration Server instance \"{{ __target_instance_name }}\"" 
          verbosity: 1
        when: (check_package_installed | bool) == false

      - name: check if source path exists on the remote
        stat: 
          path: "{{ __package_remote_source_path }}"
        register: check_package_exists

      - name: fail if package source file does not exists on the remote
        fail:
          msg: "Package source path does not exist..."
        when: not check_package_exists.stat.exists

      - name: First, delete the target folder if it exists and we are re-installing
        file:
          path: "{{ __target_package_dir }}"
          state: absent

      - name: Create target dir on the remote machine
        file:
          path: "{{ __target_package_dir }}"
          state: directory

      - name: Unarchive the packages on the remote machine
        unarchive:
          src: "{{ __package_remote_source_path }}"
          dest: "{{ __target_package_dir }}"
          remote_src: yes

      - name: Delete the archive once extracted
        file:
          path: "{{ __package_remote_source_path }}"
          state: absent

      - name: Set changed flag to true
        set_fact:
          configure_integrationserver_install_package_changed: true
  
    when: (check_package_installed | bool) == false or __target_force_reinstall_package | default() | bool