---
## expected format
# rvar_is_install_packages_list:
#   - remote_source_path: "path/to/a/package/zipfile1"
#     target_is_instance_name: default
#     target_is_package_name: "packagename1"
#     force_reinstall: yes/no
#   - remote_source_path: "path/to/a/package/zipfile2"
#     target_is_instance_name: default
#     target_is_package_name: "packagename2"
#     force_reinstall: yes/no

  - name: Packages to install
    debug: var=rvar_is_install_packages_list verbosity=3

  - name: Set changed flag to false if not defined
    set_fact: 
      configure_integrationserver_install_packages_changed: false
    when: configure_integrationserver_install_packages_changed is not defined

  - name: Installing the packages as defined in the list, only if the list is not empty
    block:

      - name: Include group tasks
        include_tasks: "do_install-package-single.yml"
        with_items: "{{ rvar_is_install_packages_list }}"
        loop_control:
          loop_var: rvar_is_install_package_single

      - name: Set changed flag to true if a change happened
        set_fact: 
          configure_integrationserver_install_packages_changed: "{{ configure_integrationserver_install_package_changed }}"

    when: rvar_is_install_packages_list is defined and (rvar_is_install_packages_list|length > 0)