---

  - debug: var=rvar_wmis_watt_params verbosity=1
  
  - debug:
      msg: "Regex: ^{{ item.key | replace('.','\\.') }}=  /// Replace Value: {{ item.key }}={{ item.value }}"
      verbosity: 1
    with_dict: "{{ rvar_wmis_watt_params }}"
    when: rvar_wmis_watt_params is defined and (rvar_wmis_watt_params|length > 0)

  - name: "Update config file {{ runtime_instance_config_file }} with new extended settings"
    lineinfile:
      state: present
      path: "{{ runtime_instance_config_file }}"
      regexp: "^{{ item.key | replace('.','\\.') }}="
      insertafter: "^#{{ item.key | replace('.','\\.') }}="
      line: "{{ item.key }}={{ item.value }}"
    with_dict: "{{ rvar_wmis_watt_params }}"
    when: rvar_wmis_watt_params is defined and (rvar_wmis_watt_params|length > 0)
