---

## Config files
wxconfig_version: "v1.10"
wxconfig_integrationserver_instance_name: "default"

_profile_instance_home: "{{ webmethods_install_dir }}/profiles/IS_{{ wxconfig_integrationserver_instance_name }}"
_runtime_instance_home: "{{ webmethods_install_dir }}/IntegrationServer/instances/{{ wxconfig_integrationserver_instance_name }}"
_runtime_instance_configs_home: "{{ _runtime_instance_home }}/config"
_runtime_instance_package_home: "{{ _runtime_instance_home }}/packages"
_wxconfig_configs_dir: "{{ _runtime_instance_configs_home }}/WxConfig"
_wxconfig_target_package_path: "{{ _runtime_instance_package_home }}/{{ rvar_wxconfig_target_package_name }}"
_wxconfig_target_package_config_path: "{{ _wxconfig_target_package_path }}/config"
_wxconfig_encrypted_values_dir: "{{ _wxconfig_configs_dir }}/EncryptedValues"
_wxconfig_license_path: "{{ _wxconfig_configs_dir }}/WxConfig_{{ wxconfig_version }}.license"

## group name represent the distinct ID for all the wxconfig files
rvar_wxconfig_unique_groupname:
rvar_wxconfig_do_remove_configs:

## install settings
rvar_wxconfig_packages: []
rvar_wxconfig_licensing: {}

## global settings values
rvar_wxconfig_global_configs: {}
rvar_wxconfig_target_package_name:

## encrypted values
rvar_wxconfig_encrypted_items: {}

## jdbc settings
rvar_wxconfig_jdbc: {}

## certs settings
rvar_wxconfig_keytruststore_list: []

## ports settings - https port
rvar_wxconfig_ports_https_list: []

## ports settings - email port
rvar_wxconfig_ports_email_list: []

## extended settings
rvar_wxconfig_extended_settings_list: []

## extended settings
rvar_wxconfig_userpassword_list: []

## ACL settings
rvar_wxconfig_groups_list:
  # - name: "groupname"
  #   updateIfExists: "true"
  #   deleteOnUnload: "false"
  #   users: []

rvar_wxconfig_acl_list:
  # - name: "aclname"
  #   updateIfExists: "true"
  #   deleteOnUnload: "false"
  #   groups:
  #     - "groupname"
  #     - "LDAP/groupname"

# if folder is set, it will be taken over the servicename value
# 'enforce' can be "always" or "topLevelOnly"
rvar_wxconfig_service_acl_mapping_list:
  # - servicename: "service"
  #   folder: "foldername"
  #   includeSubfolders: true
  #   excludes:
  #     - "pub.flow:debugLog"
  #     - "pub.flow:tracePipeline"
  #   executeACL: "ACLNAME"
  #   executeACL_enforce: "always"
  #   browseACL: "ACLNAME"
  #   readACL: "ACLNAME"
  #   writeACL: "ACLNAME"

## ldap settings
rvar_wxconfig_ldap: []
  # numberOfUsers: 10
  # credentialTimeToLiveMin: 60
  # server_list:
  #   - updateIfExists: True
  #     deleteOnUnload: False
  #     url: ""
  #     authentication:
  #       principal: ""
  #       password: ""
  #     connection:
  #       timeoutSec:
  #       poolSize_min:
  #       poolSize_max:
  #     users:
  #       synthesize:
  #         prefix:
  #         suffix:
  #       query:
  #         idproperty:
  #         rootdn:
  #     groups:
  #       default:
  #       memberattribute:
  #       query:
  #         idproperty:
  #         rootdn:

## cache managers
rvar_wxconfig_cachemanagers_list: []
  # - name: "cachemanager1"
  #   autoStart: "true"
  #   autoShutdown: "true"
  #   rejoin: "true"
  #   updateIfExists: "true"
  #   reloadOnStart: "true"
  #   destroyOnShutdown: "false"
  #   caches:
  #     - name: "cachename1"
  #       autoStart: "false" 
  #       autoShutdown: "false" 
  #       destroyOnShutdown: "false"
  #       attributes: {}
  #       terracottaConfiguration:
  #         attributes: {}
  #         nonStopConfiguration:
  #           attributes: {}
  #       searchableConfiguration:
  #         attributes: {}
  #         searchAttributes:
  #           attributes: {}
  #     - name: "cachename2"
  #       autoStart: "false" 
  #       autoShutdown: "false" 
  #       destroyOnShutdown: "false"
  #       attributes: {}
  #       terracottaConfiguration:
  #         attributes: {}
  #         nonStopConfiguration:
  #           attributes: {}
  #       searchableConfiguration:
  #         attributes: {}
  #         searchAttributes:
  #           attributes: {}
  #     - name: "cachename3"
  #       autoStart: "false" 
  #       autoShutdown: "false" 
  #       destroyOnShutdown: "false"
  #       attributes: {}
  #       terracottaConfiguration:
  #         attributes: {}
  #         nonStopConfiguration:
  #           attributes: {}
  #       searchableConfiguration:
  #         attributes: {}
  #         searchAttributes:
  #           attributes: {}

## integration server messaging objects
## format on these lists are the expected field names by wxconfig
rvar_wxconfig_is_messaging_wmalias_list: []
rvar_wxconfig_is_messaging_wmtriggers_list: []
rvar_wxconfig_is_messaging_jndi_list: []
rvar_wxconfig_is_messaging_jmsalias_list: []
rvar_wxconfig_is_messaging_jmstriggers_list: []
  
## adapter connections
## format on these lists are the expected field names by wxconfig
rvar_wxconfig_adapter_connections_list: []

## schedulers
rvar_wxconfig_schedulers_list: []

## remote servers
rvar_wxconfig_remoteservers_list: []