---

## Config files
product_instance_name: "default"
_profile_instance_home: "{{ webmethods_install_dir }}/profiles/IS_{{ product_instance_name }}"
_runtime_instance_home: "{{ webmethods_install_dir }}/IntegrationServer/instances/{{ product_instance_name }}"
_runtime_instance_configs_home: "{{ _runtime_instance_home }}/config"
_runtime_instance_package_home: "{{ _runtime_instance_home }}/packages"
_wxconfig_configs_dir: "{{ _runtime_instance_configs_home }}/WxConfig"
_wxconfig_target_package_path: "{{ _runtime_instance_package_home }}/{{ rvar_wxconfig_target_package_name }}"
_wxconfig_target_package_config_path: "{{ _wxconfig_target_package_path }}/config"
_wxconfig_encrypted_values_dir: "{{ _wxconfig_configs_dir }}/EncryptedValues"

## group name represent the distinct ID for all the wxconfig files
rvar_wxconfig_unique_groupname:
rvar_wxconfig_do_remove_configs:

## install settings
rvar_wxconfig_packages: []
rvar_wxconfig_licensing: {}

## global settings values
rvar_wxconfig_global_configs: {}
rvar_wxconfig_target_package_name:

## encrypted values
rvar_wxconfig_encrypted_items: {}

## jdbc settings
rvar_wxconfig_jdbc: {}

## certs settings
rvar_wxconfig_keytruststore_list: []

## ports settings
rvar_wxconfig_ports_https_list: []

## extended settings
rvar_wxconfig_extended_settings_list: []

## extended settings
rvar_wxconfig_userpassword_list: []

## ACL settings
rvar_wxconfig_groups_list:
  # - name: "groupname"
  #   updateIfExists: "true"
  #   deleteOnUnload: "false"
  #   users: []

rvar_wxconfig_acl_list:
  # - name: "aclname"
  #   updateIfExists: "true"
  #   deleteOnUnload: "false"
  #   groups:
  #     - "groupname"
  #     - "LDAP/groupname"

# if folder is set, it will be taken over the servicename value
# 'enforce' can be "always" or "topLevelOnly"
rvar_wxconfig_service_acl_mapping_list:
  # - servicename: "service"
  #   folder: "foldername"
  #   includeSubfolders: true
  #   excludes:
  #     - "pub.flow:debugLog"
  #     - "pub.flow:tracePipeline"
  #   executeACL: "ACLNAME"
  #   executeACL_enforce: "always"
  #   browseACL: "ACLNAME"
  #   readACL: "ACLNAME"
  #   writeACL: "ACLNAME"

## ldap settings
rvar_wxconfig_ldap: []
  # numberOfUsers: 10
  # credentialTimeToLiveMin: 60
  # server_list:
  #   - updateIfExists: True
  #     deleteOnUnload: False
  #     url: ""
  #     authentication:
  #       principal: ""
  #       password: ""
  #     connection:
  #       timeoutSec:
  #       poolSize_min:
  #       poolSize_max:
  #     users:
  #       synthesize:
  #         prefix:
  #         suffix:
  #       query:
  #         idproperty:
  #         rootdn:
  #     groups:
  #       default:
  #       memberattribute:
  #       query:
  #         idproperty:
  #         rootdn: