---

## Config files
integrationserver_instance_name: "default"
_runtime_profile_home: "{{ webmethods_install_dir }}/profiles/IS_{{ integrationserver_instance_name }}"
_runtime_instance_home: "{{ webmethods_install_dir }}/IntegrationServer/instances/{{ integrationserver_instance_name }}"
_runtime_instance_package_home: "{{ _runtime_instance_home }}/packages"
_runtime_instance_config_home: "{{ _runtime_instance_home }}/config"
_runtime_instance_config_file: "{{ _runtime_instance_config_home }}/server.cnf"
_custom_wrapper_file: "{{ _runtime_profile_home }}/configuration/custom_wrapper.conf"

## licenses
### IS
_is_license_path: "{{ _runtime_instance_config_home }}/licenseKey.xml"
_is_license_inzip_src_path:

### EntireX
_is_exx_license_path: "{{ _runtime_instance_config_home }}/license.entirex.xml"
_is_exx_license_inzip_src_path:

### Terracotta
_is_terracotta_license_path: "{{ webmethods_install_dir }}/common/conf/terracotta-license.key"
_is_terracotta_license_inzip_src_path:

## connectivity to external terracotta
rvar_is_terracotta_connect_port: 9510

## install package
rvar_is_install_packages_list: []
rvar_is_install_packages_force_reinstall_list: []