---

- debug:
    msg: "Running provision-with-installer"

- debug: var=rvar_install_products_descriptor_list verbosity=3

- include_tasks: "install.yml"
  with_items: "{{ rvar_install_products_descriptor_list }}"
  loop_control:
    loop_var: rvar_install_products_descriptor