---
## for info about input variable rvar_jvm_params,
## see sagdevops-ansible-common-webmethods/roles/configure-jvm-wrapper/tasks/do_set-jvm-params.yml

- import_role:
    name: configure-jvm-wrapper
  vars:
    configs_action: set-jvm-params
    rvar_wrapper_file: "{{ _tc_custom_wrapper_file }}"
