---

  - debug: var=rvar_mws_command_param_list verbosity=1

  - name: base executable
    set_fact:
      command_to_exec: [ './mws.sh' ]

  - name: append instance params
    set_fact:
      command_to_exec: "{{ command_to_exec }} + {{ rvar_mws_command_param_list | default([]) }}"

  - name: Print the command that we're going to run
    debug:
      msg: "About to run: {{ command_to_exec|join(' ') }}"
      verbosity: 1

  - name: execute command
    command:
      argv: "{{ command_to_exec }}"
      chdir: "{{ _mws_command_dir }}"
    register: cmd_result

  - name: Print the cmd_result to the console.
    debug:
      msg: "{{ cmd_result.stdout_lines | join('\n') }}"
      verbosity: 1